package com.spring.spring_6_rest_mvc.models;

import jakarta.validation.constraints.*;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Data
@Builder
public class BeerDTO {

    // generated by hibernate
    @Null
    private UUID id;
    @Null
    private Integer version;

    // managed by the backend
    @Null
    private LocalDateTime createdDate;
    @Null
    private LocalDateTime updateDate;

    // received from client
    @NotBlank
    private String beerName;

    @NotNull
    private BeerStyle beerStyle;

    @NotBlank
    @Pattern(regexp = "\\d+")
    @Size(min = 12, max = 12)
    private String upc;

    @Positive
    @NotNull
    private Integer quantityOnHand;

    @Positive
    @NotNull
    private BigDecimal price;

}
