package com.spring.spring_6_rest_mvc.models;


import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Pattern;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
@Builder
public class CustomerDTO {

    // generated by hibernate
    @Null
    private UUID id;
    @Null
    private Integer version;

    // managed by the backend
    @Null
    private LocalDateTime createDate;
    @Null
    private LocalDateTime lastModifiedDate;

    // received from client
    @NotBlank
    private String customerName;

}
